[package]
name = "byterepr"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/byterepr"

[lib]
name = "byterepr"
path = "lib.rs"
